[build]
  # Build command includes dashboard and functions using Bun
  command = "bun install && bun run build && cd dashboard && bun install && bun run build"
  # Directory to publish
  publish = "dashboard/dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version for Netlify functions compatibility
  NODE_VERSION = "18"
  # Build environment
  NODE_ENV = "production"

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API routes handled by Netlify functions (MUST come before catch-all)
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]  
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# MCP SSE endpoint handled by Netlify function
[[redirects]]
  from = "/mcp/sse"
  to = "/.netlify/functions/mcp-sse"
  status = 200

# SSE endpoint handled by Netlify function  
[[redirects]]
  from = "/sse"
  to = "/.netlify/functions/api"
  status = 200

# Root endpoint handled by API function for service landing page
[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# Health and metrics endpoints
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/metrics"
  to = "/.netlify/functions/api"
  status = 200

# SPA routing configuration for dashboard (MUST come after API routes)
[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200

