[build]
  command = "bun install && bun run build"
  functions = "netlify/functions"
  publish = "dashboard/dist"

[build.environment]
  # Node.js version for Netlify functions compatibility
  NODE_VERSION = "18"
  # Build environment
  NODE_ENV = "production"
  # Note: Supabase environment variables (SUPABASE_URL, SUPABASE_SERVICE_KEY) 
  # must be set in Netlify Dashboard → Site Settings → Environment Variables

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CORE ALIGNMENT: MCP endpoints with proper WebSocket path support
[[redirects]]
  from = "/mcp/ws"
  to = "/.netlify/functions/mcp-sse"
  status = 200

[[redirects]]
  from = "/mcp/sse"
  to = "/.netlify/functions/mcp-sse"
  status = 200
  force = true

# Domain-specific redirects for Dashboard domain

# NOTE: MCP domain (mcp.lanonasis.com) routing is handled by the onasis-core project
# This public repo should NOT interfere with MCP routing to avoid affecting other services

# Legacy MCP path support (will be deprecated)
[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp-sse"
  status = 200

# CORE ALIGNMENT: Service discovery endpoint (MUST come first)
[[redirects]]
  from = "/.well-known/onasis.json"
  to = "/.netlify/functions/api-new"
  status = 200

# API routes handled by Netlify functions (MUST come before catch-all)
[[redirects]]
  from = "https://dashboard.lanonasis.com/*"
  to = "/index.html"
  status = 200

# API redirects - fixed paths
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api-new/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-new/:splat"
  status = 200

# Root endpoint handled by React dashboard (landing page integrated into SPA)
# Removed redirect to API function - dashboard now serves landing page

# Health and metrics endpoints
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api-new"
  status = 200

[[redirects]]
  from = "/metrics"
  to = "/.netlify/functions/api-new"
  status = 200

# Domain-specific routing for api.lanonasis.com - Redirect auth/dashboard to dashboard domain
[[redirects]]
  from = "/dashboard*"
  to = "https://dashboard.lanonasis.com/dashboard"
  status = 302
  conditions = {Host = ["api.lanonasis.com"]}

[[redirects]]
  from = "/auth*"
  to = "https://dashboard.lanonasis.com/"
  status = 302
  conditions = {Host = ["api.lanonasis.com"]}

[[redirects]]
  from = "/"
  to = "https://dashboard.lanonasis.com/"
  status = 302
  conditions = {Host = ["api.lanonasis.com"]}

# Documentation routing for docs.lanonasis.com domain
[[redirects]]
  from = "/*"
  to = "/docs/:splat"
  status = 200
  conditions = {Host = ["docs.lanonasis.com"]}

# Dashboard domain routing - SPA handles all routes for dashboard.lanonasis.com
# Auth callback handling for OAuth - MUST come before SPA catch-all
[[redirects]]
  from = "/auth/callback*"
  to = "/index.html"
  status = 200
  conditions = {Host = ["dashboard.lanonasis.com"]}

# All other dashboard routes - SPA handles routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Host = ["dashboard.lanonasis.com"]}

# API domain routing - serve API function for api.lanonasis.com (MUST be LAST)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api-new"
  status = 200
  conditions = {Host = ["api.lanonasis.com"]}
