[build]
  # Build command includes dashboard and functions using Bun
  command = "bun install && bun run build && cd dashboard && bun install && bun run build"
  # Directory to publish
  publish = "dashboard/dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version for Netlify functions compatibility
  NODE_VERSION = "18"
  # Build environment
  NODE_ENV = "production"
  # Note: Supabase environment variables (SUPABASE_URL, SUPABASE_SERVICE_KEY) 
  # must be set in Netlify Dashboard → Site Settings → Environment Variables

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# MCP SSE endpoints MUST come first before API routes
[[redirects]]
  from = "/mcp/sse"
  to = "/.netlify/functions/mcp-sse"
  status = 200

[[redirects]]
  from = "/sse"
  to = "/.netlify/functions/mcp-sse"
  status = 200

# API routes handled by Netlify functions (MUST come before catch-all)
[[redirects]]
  from = "/api/v1/orchestrate"
  to = "/.netlify/functions/orchestrate"
  status = 200

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]  
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Root endpoint handled by React dashboard (landing page integrated into SPA)
# Removed redirect to API function - dashboard now serves landing page

# Health and metrics endpoints
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/metrics"
  to = "/.netlify/functions/api"
  status = 200

# Documentation routing for docs.lanonasis.com domain
[[redirects]]
  from = "/*"
  to = "/docs/:splat"
  status = 200
  conditions = {Host = ["docs.lanonasis.com"]}

# Dashboard domain routing - SPA handles all routes for dashboard.lanonasis.com
# Auth callback handling for OAuth - MUST come before SPA catch-all
[[redirects]]
  from = "/auth/callback*"
  to = "/index.html"
  status = 200
  conditions = {Host = ["dashboard.lanonasis.com"]}

# All other dashboard routes - SPA handles routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Host = ["dashboard.lanonasis.com"]}
