// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL=https://<project-ref>.supabase.co
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY=REDACTED_SUPABASE_ANON_KEY

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Determine correct redirect URL based on environment
const getRedirectUrl = () => {
  if (typeof window === 'undefined') return 'https://dashboard.lanonasis.com';
  const isLocalDev = window.location.hostname === 'localhost';
  return isLocalDev ? window.location.origin : 'https://dashboard.lanonasis.com';
};

export const supabase = createClient<Database>(SUPABASE_URL=https://<project-ref>.supabase.co
  auth: {
    flowType: 'pkce'
  }
});